api: {}


log:
  level: INFO


providers:
  docker: {}


entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"


certificatesResolvers:
  mytlschallenge:
    acme:
      email: riepl.privat@gmail.com
      storage: ./acme.json
      httpChallenge:
        entryPoint: http
      tlsChallenge: {}
